camera: hik

odom2camera:

  xyz: "\"0.12 0.06 0.03\""
  rpy: "\"0.0  0.0  0.0\""

armor_detector_log_level: INFO
armor_tracker_log_level: INFO
# buff_detector_log_level: INFO
# buff_tracker_log_level: INFO
serial_log_level: INFO
#auto_record_log_level: INFO